COPY atomic.events FROM 's3://au-com-blinkmobile-analytics-ap-southeast-2/emr/enriched/good/' CREDENTIALS 'aws_access_key_id=AKIAJKYF2U6LJFWL4JHQ;aws_secret_access_key=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' REGION AS 'ap-southeast-2' DELIMITER '\t' MAXERROR 1 EMPTYASNULL FILLRECORD TRUNCATECOLUMNS  TIMEFORMAT 'auto' ACCEPTINVCHARS;
--
COPY atomic.co_blinkmobile_page_1 FROM 's3://au-com-blinkmobile-analytics-ap-southeast-2/emr/shredded/good/run=2015-05-13-14-31-50/co.blinkmobile/page/jsonschema/1-' CREDENTIALS 'aws_access_key_id=AKIAJKYF2U6LJFWL4JHQ;aws_secret_access_key=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' JSON AS 's3://au-com-blinkmobile-analytics-ap-southeast-2/jsonpaths/co.blinkmobile/page_1.json' REGION AS 'ap-southeast-2' MAXERROR 1 TRUNCATECOLUMNS TIMEFORMAT 'auto' ACCEPTINVCHARS;
--
COPY atomic.co_blinkmobile_user_1 FROM 's3://au-com-blinkmobile-analytics-ap-southeast-2/emr/shredded/good/run=2015-05-13-14-31-50/co.blinkmobile/user/jsonschema/1-' CREDENTIALS 'aws_access_key_id=AKIAJKYF2U6LJFWL4JHQ;aws_secret_access_key=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' JSON AS 's3://au-com-blinkmobile-analytics-ap-southeast-2/jsonpaths/co.blinkmobile/user_1.json' REGION AS 'ap-southeast-2' MAXERROR 1 TRUNCATECOLUMNS TIMEFORMAT 'auto' ACCEPTINVCHARS;
--
COPY atomic.com_snowplowanalytics_snowplow_link_click_1 FROM 's3://au-com-blinkmobile-analytics-ap-southeast-2/emr/shredded/good/run=2015-05-13-14-31-50/com.snowplowanalytics.snowplow/link_click/jsonschema/1-' CREDENTIALS 'aws_access_key_id=AKIAJKYF2U6LJFWL4JHQ;aws_secret_access_key=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' JSON AS 's3://au-com-blinkmobile-analytics-ap-southeast-2/jsonpaths/com.snowplowanalytics.snowplow/link_click_1.json' REGION AS 'ap-southeast-2' MAXERROR 1 TRUNCATECOLUMNS TIMEFORMAT 'auto' ACCEPTINVCHARS;
--
COPY atomic.com_snowplowanalytics_page_1 FROM 's3://au-com-blinkmobile-analytics-ap-southeast-2/emr/shredded/good/run=2015-05-13-14-31-50/com.snowplowanalytics/page/jsonschema/1-' CREDENTIALS 'aws_access_key_id=AKIAJKYF2U6LJFWL4JHQ;aws_secret_access_key=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' JSON AS 's3://au-com-blinkmobile-analytics-ap-southeast-2/jsonpaths/com.snowplowanalytics/page_1.json' REGION AS 'ap-southeast-2' MAXERROR 1 TRUNCATECOLUMNS TIMEFORMAT 'auto' ACCEPTINVCHARS;
--
COPY atomic.com_snowplowanalytics_user_2 FROM 's3://au-com-blinkmobile-analytics-ap-southeast-2/emr/shredded/good/run=2015-05-13-14-31-50/com.snowplowanalytics/user/jsonschema/2-' CREDENTIALS 'aws_access_key_id=AKIAJKYF2U6LJFWL4JHQ;aws_secret_access_key=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' JSON AS 's3://au-com-blinkmobile-analytics-ap-southeast-2/jsonpaths/com.snowplowanalytics/user_2.json' REGION AS 'ap-southeast-2' MAXERROR 1 TRUNCATECOLUMNS TIMEFORMAT 'auto' ACCEPTINVCHARS;
--
COPY atomic.org_w3_performance_timing_1 FROM 's3://au-com-blinkmobile-analytics-ap-southeast-2/emr/shredded/good/run=2015-05-13-14-31-50/org.w3/PerformanceTiming/jsonschema/1-' CREDENTIALS 'aws_access_key_id=AKIAJKYF2U6LJFWL4JHQ;aws_secret_access_key=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' JSON AS 's3://au-com-blinkmobile-analytics-ap-southeast-2/jsonpaths/org.w3/performance_timing_1.json' REGION AS 'ap-southeast-2' MAXERROR 1 TRUNCATECOLUMNS TIMEFORMAT 'auto' ACCEPTINVCHARS;
